Ensembl/ensembl-genomio

scripts/gff_metaparser/conf/valid_structures.conf
Minor additions to valid_structure configuration file.
=> Updated valid_structures.conf to accout for MAKER2 UTR gene models

lib/perl/Bio/EnsEMBL/Pipeline/Runnable/BRC4/DumpGenomeJson.pm, schema/genome_schema.json, scripts/gff_metaparser/gen_meta_conf.py, scripts/gff_metaparser/genmetaconf/metaconf.py
Enabling "species.annotation_source" and "genebuild.method_display" meta data (optional keys) support.
Loading pipeline loads.
=> Vsitnik new attribs

data/external_db_map_default.txt, scripts/gff_metaparser/conf/gff_metaparser.conf, scripts/gff_metaparser/conf/gff_metaparser/flybase.conf, scripts/gff_metaparser/conf/valid_structures.conf, scripts/gff_metaparser/genmetaconf/metaconf.py
metazoan part configs and script
=> FlyBase update related fixes

lib/perl/Bio/EnsEMBL/Pipeline/Runnable/EG/LoadGFF3/ApplySeqEdits.pm, lib/perl/Bio/EnsEMBL/Pipeline/Runnable/EG/LoadGFF3/FixModels.pm, lib/perl/Bio/EnsEMBL/Pipeline/Runnable/EG/LoadGFF3/ReportSeqEdits.pm
Retrieving translation sequences can be very slow when the seq_regions are very long, because then we can't take advantage of the cache.
These commits change the loops from all transcripts, to all slices, all of them split up so that they be cached.
=> Optimize slice cache

scripts/brc4/patch_build/allocate_stable_ids.pl
Required otherwise the xref addition will fail
=> Fix: ignore release to store xref

scripts/gff_metaparser/genmetaconf/seqregionconf.py
fill cs_tag from "Assigned-Molecule-Location/Type" only if "Sequence-Role" is ""assembled-molecule"
=> fill cs_tag from  assembly_report  only for "assembled-molecule" entries

pyproject.toml
Pending BCBio fix: https://github.com/chapmanb/bcbb/pull/137
=> Fix Bio versions to avoid deprecated calls

docs/trf_split_run.md, scripts/trf_split_run.bash
use ENSEMBL_ROOT_DIR env instead of #ensembl_cvs_root_dir# for pipeline tweaking
=> trf split run documentation update

docs/trf_split_run.md, scripts/trf_split_run.bash
adding DNA_FEATURES_TRF_SPLIT_TRF_OPTIONS to be appended to the trf params in trf_split_run.bash
=> DNA_FEATURES_TRF_SPLIT_TRF_OPTIONS env var for trf_split_run.bash

src/python/ensembl/brc4/runnable/process_seq_region.py
Use the list of sources in order (so GenBank first). For EBI, use whatever is used for the name.
=> Fix BRC4/EBI seq region names

pipelines/nextflow/modules/manifest_stats.nf, pipelines/nextflow/subworkflows/additional_seq_prepare.nf, pyproject.toml, src/python/ensembl/io/genomio/__init__.py, src/python/ensembl/io/genomio/manifest_stats.py
Work as part of the Nextflow Hackathon
=> Manifest stats hackathon-Ahmad & Zahra

src/perl/Bio/EnsEMBL/Pipeline/PipeConfig/LoadGFF3Batch_conf.pm, src/perl/Bio/EnsEMBL/Pipeline/PipeConfig/LoadGFF3_conf.pm
Using BRC4_base_conf instead of EGGeneric_conf for resources
=> added BRC4_base_conf

scripts/brc4/patch_build/allocate_stable_ids.pl
Dump the gene mapping new_id, old_id
in a format acceptable by the event loader
=> Add option out_gene_map to dump

src/python/ensembl/io/genomio/download_genbank.py, src/python/ensembl/io/genomio/extract_from_gb.py
Replicating the changes in nextflow to use locus_tag as gene name when required and adding support for pseudogene in the gff while adding an organellar sequence. 
Derived from this commit by Matthieu
https://github.com/Ensembl/ensembl-genomio/pull/78
=> replicating the changes made by Matthieu in nextflow

cicd/gitlab/dot.gitlab-ci.yml, cicd/gitlab/parts/python.gitlab-ci.yml, pyproject.toml
Following the discussions in our software development meeting. I have also taken the liberty to add the coverage report bit.
_Note:_ I have reverted the `ensembl-hive` temporary "fix", but everything should work once the actual fix is merged in ensembl-py ([PR#27](https://github.com/Ensembl/ensembl-py/pull/27)).
=> Updates and testing additions to CI/CD

cicd/gitlab/parts/python.gitlab-ci.yml, pyproject.toml
Missing "coverage" dependency (I thought it was installed as a dependency of "pytest").
=> Resolve missing dependencies

src/python/tests/conftest.py, src/python/tests/metadata/test_prepare_genome.py, src/python/tests/test_integrity.py, src/python/tests/test_schemas.py
=> Test dirs as simple fixture

src/python/ensembl/io/genomio/extract_from_gb.py
Adding support for tRNA and rRNA
=> modifying the parser to include tRNA and rRNA in gff

src/perl/Bio/EnsEMBL/Pipeline/PipeConfig/BRC4_genome_loader_conf.pm, src/python/ensembl/brc4/runnable/integrity.py, src/python/ensembl/brc4/runnable/manifest.py, src/python/ensembl/brc4/runnable/manifest_stats.py, src/python/ensembl/io/genomio/integrity.py
ensembl.brc4.runnable.schema_validator -> exec check_json
ensembl.brc4.runnable.utils ->  ensembl.io.genomio.utils.json_utils
=> Loader fix

src/perl/Bio/EnsEMBL/Pipeline/PipeConfig/BRC4_genome_dumper_conf.pm
No a complete transition, but enough to make the dumper pipeline run with the current code base
=> Use genome/io check_json_schema

src/python/ensembl/io/genomio/metadata/update_genome_metadata.py
Also remove version numbers for comparison
Currently the code would erronously list most of the IDs if from RefSeq.
=> Compare gb id with both refseq and genbank

src/python/ensembl/io/genomio/manifest_stats.py
The stats file should be wherever we want (and with the name we choose), not necessarily in the manifest directory. This is needed for better nextflow support.
=> Explicit stats_file path parameter

pipelines/nextflow/modules/gff3/process_gff3.nf, pipelines/nextflow/modules/manifest/manifest_maker.nf, pipelines/nextflow/modules/manifest/manifest_stats.nf, pipelines/nextflow/workflows/nextflow.config
Start adaptive at 4GB
Also include both 137 and 140 error codes for retry
=> Apply better resources for hungry processes

scripts/gff_metaparser/gen_meta_conf.py, scripts/gff_metaparser/genmetaconf/metaconf.py, scripts/gff_metaparser/genmetaconf/seqregionconf.py
1) no species alias generated by default
2) seq_region location can be taken from assembly_report
=> metazoa gen_meta_conf update

pipelines/nextflow/workflows/nextflow.config
https://www.nextflow.io/docs/latest/config.html?highlight=queueglobalstatus#scope-executor
Taken the opportunity to simplify the profiles putting the variables in their corresponding blocks to ease learning and tracking. I have also merged other suggestions from the EBI Nextflow config proposal [[link](https://github.com/nf-core/configs/blob/master/conf/ebi_codon.config)].
=> Apply updates to SLURM profile following conversation with TSC

pipelines/nextflow/modules/download/download_genbank.nf, pipelines/nextflow/modules/files/collect_files.nf, pipelines/nextflow/modules/genbank/extract_from_gb.nf, pipelines/nextflow/subworkflows/additional_seq_prepare/main.nf, pipelines/nextflow/workflows/additional_seq_prepare/main.nf
Cleaner approach: all species specific information are put in the meta key.
=> Group species params into a meta key

pipelines/nextflow/modules/files/collect_files.nf, pipelines/nextflow/subworkflows/additional_seq_prepare/main.nf
Fix the broken genome_prepare pipeline (introduced by the partial meta key update in my previous PR).
=> Collect files is used by other pipelines, fallback

.gitignore, pipelines/nextflow/modules/gff3/process_gff3.nf, src/python/ensembl/io/genomio/gff3/process_gff3.py
- Update made to gitignore to exclude docs/source
- General Changes made to python module to tidy and help readability, also includes first use of doc string module description to be displayed with `--help`
- Update to NXF process_gff3 module (remove enable DLS, script -> shell and remove def on var declares)
=> Updates to NXF module, and python module related to process_GFF3

pipelines/nextflow/workflows/additional_seq_prepare/main.nf
Suggestion in a separate PR since we can't make suggestions on unchanged files
=> Fix addition prepare call

src/python/ensembl/io/genomio/assembly/get_assembly_data.py, src/python/ensembl/io/genomio/events/format_events.py, src/python/ensembl/io/genomio/fastaprep/process_fasta.py, src/python/ensembl/io/genomio/genbank/extract_from_genbank.py, src/python/ensembl/io/genomio/genbank/get_genbank.py, src/python/ensembl/io/genomio/genome_metadata/compare_genome_stats.py, src/python/ensembl/io/genomio/genome_metadata/dump_genome_metadata.py, src/python/ensembl/io/genomio/genome_metadata/dump_genome_stats.py, src/python/ensembl/io/genomio/gff3/__init__.py, src/python/ensembl/io/genomio/gff3/functional_annotation.py, src/python/ensembl/io/genomio/gff3/process_gff3.py, src/python/ensembl/io/genomio/integrity.py, src/python/ensembl/io/genomio/manifest_stats.py, src/python/ensembl/io/genomio/metadata/prepare_genome.py, src/python/ensembl/io/genomio/metadata/prepare_seq_region.py, src/python/ensembl/io/genomio/metadata/update_genome_metadata.py, src/python/ensembl/io/genomio/utils/archive_utils.py
I haven't done this for the single-file modules, as I believe some of these may be relocated soon.
=> Address some missing elements to control module imports correctly

.github/workflows/sphinx_doc_generation.yaml
Revert changes to event trigger from push to pull_request
- Adding also the conditional that the event PR is merged
=> Changes to trigger event of docs workflow 

src/python/tests/test_workflow_trigger.py
One last try to trigger docs workflow. 
Copied existing pythong test to new file. Will delete once PR is merged, regardless of Workflow success
=> Create temp python test to trigger docs wf

src/python/ensembl/brc4/runnable/fill_metadata.py, src/python/ensembl/brc4/runnable/load_sequence_data.py, src/python/ensembl/io/genomio/assembly/get_assembly_data.py, src/python/ensembl/io/genomio/gff3/process_gff3.py, src/python/ensembl/io/genomio/integrity.py, src/python/ensembl/io/genomio/metadata/prepare_genome.py, src/python/ensembl/io/genomio/metadata/prepare_seq_region.py, src/python/ensembl/io/genomio/metadata/update_genome_metadata.py, src/python/ensembl/io/genomio/schemas/json_schema_factory.py, src/python/ensembl/io/genomio/seq_region_dumper.py, src/python/ensembl/io/genomio/utils/archive_utils.py
Added new include/exclude features, including some additional processing for IG/T-cell elements to be converted to the corresponding biotype.
We also agreed that it seems the best that the code merges split genes by default and generates a report of the merged genes that can be reviewed in case something doesn't look right.
=> Added new features following B67 production

src/python/ensembl/io/genomio/events_loader.py
Moreover, I have made the class' messages more self-explanatory.
=> Bugfix: include initial event for each release

pipelines/nextflow/modules/events/dump_events.nf, pipelines/nextflow/modules/patch_build/load_events.nf, src/python/ensembl/brc4/runnable/core_server.py, src/python/ensembl/io/genomio/events/dump.py, src/python/ensembl/io/genomio/events/load.py
Merging event module changes into ancestor branch lcampbell/assembly_download
=> Implement ensembl-py logging events module

src/python/ensembl/io/genomio/fasta/process.py
to replace outdated and closed  https://github.com/Ensembl/ensembl-genomio/pull/206
=> adding logging to ensembl.io.genomio.fasta.process

src/python/ensembl/io/genomio/seq_region/dump.py, src/python/ensembl/io/genomio/seq_region/prepare.py
Seq_region module
1. Dump.py: did not have a lot of print messages so just removed some commented lines
2. Prepare.py: I have used warn where necessary, I have not used the debug option but I have mentioned it in the args just incase we use it in future.
=> Adding log to seq_region module

pipelines/nextflow/modules/genome_metadata/dump_genome_meta.nf, pipelines/nextflow/modules/seq_region/dump_seq_regions.nf
Couple of simple fixes for the dumpers
=> update schema call for dumpers

src/perl/Bio/EnsEMBL/Pipeline/PipeConfig/BRC4_genome_loader_conf.pm
Remove boolean operands for params converted to optional flag
=> Update manifest_integrity params

pipelines/nextflow/modules/gff3/gff3_validation.nf
Updating the container so trace parameter can run smoothly
=> updating the container as we require ps for tracing

pyproject.toml
Updated based on the versions I have installed in a working virtual environment, after testing all of them with our current codebase.
=> Update minimum versions of main CI/CD and documentation tools

pyproject.toml
Final bit of conflict resolution before merging back to main
=> Resolve conflict to prepare merging hackathon/dec23 to main

LICENSE, README.md
LICENSE: added missing copyright owner info 
README: just added the license badge
=> updated LICENSE and README files

src/python/ensembl/io/genomio/genbank/extract_data.py
Fix for mypy + broken DIct type
=> Fix Dict type

src/python/ensembl/io/genomio/genbank/extract_data.py
I assume this went ok because we've only loaded single extra sequences until now.
We should add some testing with more than 1 record at some point.
=> Format outside record loop

pyproject.toml, src/python/ensembl/io/genomio/genome_metadata/prepare.py, src/python/tests/genome_metadata/test_extend.py
Merge + disable pylint for private method test
=> Merge main to hackathon

src/python/ensembl/io/genomio/gff3/extract_annotation.py, src/python/tests/gff3/test_extract_annotation.py
Add test for get_xrefs and fix a bug when the DB xref value contains a colon
=> Add xref test, fix small bug

scripts/gff_metaparser/genmetaconf/metaconf.py
tested on metazoam load of `rs8t_mgen/metadata`
=> fixing BioSample typo and adding more RR/MVP related meta_key duplicates

src/python/ensembl/io/genomio/gff3/extract_annotation.py
It was easier to do this suggestion in a PR than as a review.
=> Simplify code to avoid using flags

src/python/ensembl/io/genomio/gff3/extract_annotation.py, src/python/tests/gff3/test_simplifier.py
Somehow logging module was removed but was necessary. Also fix a test.
=> Fix after merge

src/python/ensembl/io/genomio/assembly/status.py
Updated default version to latest ncbi-datasets version 16.12.1
=> Update status.py datasets version - 16.12.1

.github/workflows/mkdocs_docs_generation.yml, README.md
I have renamed the workflow to make the badge a little bit more "human readable".
=> Add documentaiton badge with quick link to GitHub pages

cicd/gitlab/dot.gitlab-ci.yml, cicd/gitlab/parts/containers.gitlab-ci.yml, cicd/gitlab/parts/flatfile.gitlab-ci.yml, containers/docker/datasets-cli/Dockerfile
=> Fixes from Jalvarez/cicd_containers

pipelines/nextflow/workflows/nextflow.config
This should be a per-user configuration, not by default
=> Disable notification in main nextflow.config

cicd/gitlab/parts/python.gitlab-ci.yml, docs/BRC4_genome_compare_conf.md, docs/nextflow.md, src/python/ensembl/io/genomio/annotation/load.py, src/python/ensembl/io/genomio/genbank/extract_data.py, src/python/ensembl/io/genomio/gff3/extract_annotation.py, src/python/ensembl/io/genomio/manifest/check_integrity.py, src/python/ensembl/io/genomio/manifest/compute_stats.py, src/python/ensembl/io/genomio/seq_region/__init__.py, src/python/ensembl/io/genomio/seq_region/dump.py, src/python/ensembl/io/genomio/seq_region/rename.py, src/python/tests/assembly/test_download.py, src/python/tests/database/test_dbconnection_lite.py, src/python/tests/genbank/test_extract_data.py, src/python/tests/gff3/test_extract_annotation.py, src/python/tests/gff3/test_restructure.py
This may not be too comprehensive, but it is a good first look.
=> Minor codebase review looking for typos and other missing elements

scripts/gff_metaparser/gffstruct/rules/fix_action.py, scripts/gff_metaparser/gffstruct/rules/json.py
tested on ensembl-production-metazoa/meta/2024-07.113_for_114/dmel
=> recovering after bcbio update from 1-based to 0-based starts

pipelines/nextflow/modules/patch_build/canonical_transcripts.nf
Proper name for the process and use correct mysql arguments, for the patch build pipeline.
=> Fix process name and mysql arguments

config/gff_metaparser/metaparser.conf, config/gff_metaparser/metaparser/flybase.conf
=> fixing transposable_element JSON path in metaparser configs

src/python/ensembl/io/genomio/gff3/overlaps.py
Small fix to amend recent Merge on code without full black formatting.
=> Black-ify overlaps fix cicd

pipelines/nextflow/modules/events/dump_events.nf, pipelines/nextflow/subworkflows/dump_files/main.nf, pipelines/nextflow/workflows/dumper_pipeline/main.nf, pyproject.toml, src/python/ensembl/io/genomio/events/__init__.py, src/python/ensembl/io/genomio/events/dump.py, src/python/ensembl/io/genomio/events/format.py, src/python/ensembl/io/genomio/events/load.py
I have restored the files that could be used in Stable_id_allocation.
=> restore the stable_id allocation files

config/gff_metaparser/valid_structures.conf
Issue found in e115, this fixed it.
=> Ignore UTRs of genes
