lib/python/ensembl/brc4/runnable/process_gff3.py
Right now we don't load pseudogenes_with_CDS at the step LoadGFF3, but we should exclude them when we prepare the data already.
=> by default remove cds from pseudogenes

README.md, docs/trf_split_run.md, scripts/chunk_fasta.py, scripts/trf_split_run.bash
A trf wrapper with chunking support to be used with DNAFeatures pipeline
Compatible with  input/output format of trf invocation from  Bio::EnsEMBL::Analysis::Runnable::TRF
(https://github.com/Ensembl/ensembl-analysis/blob/main/modules/Bio/EnsEMBL/Analysis/Runnable/TRF.pm)
Can be used as a hack to allow TRF stage to be accomplished at the cost of splitting long repeat into several adjacent ones (with possible losses).
=> trf wrapper with chunking support to be used with the TRF stage of the DNAFeatures pipeline

pyproject.toml
This library is no longer maintained and it is not compatible with click v8.0 (needed by other libraries and `black`).
Unfortunately, I have not been able to find a suitable replacement from a quick search.
=> Removed deprecated dependency

cicd/gitlab/dot.gitlab-ci.yml, cicd/gitlab/parts/license.gitlab-ci.yml, pyproject.toml
Added new CI/CD pipeline for License-related checks, starting for checking if the NOTICE file has the latest copyright year.
I have also taken the opportunity to do a small change in the coverage check to use the library namespace instead of the source, so if GenomIO is not installed with `-e` it should still return the right coverage information.
=> NOTICE copyright year check

cicd/gitlab/parts/license.gitlab-ci.yml, cicd/gitlab/scripts/license_header.sh, docs/source/conf.py, pipelines/nextflow/modules/download_genbank.nf, pipelines/nextflow/modules/extract_from_gb.nf, pipelines/nextflow/modules/gff3_validation.nf, pipelines/nextflow/modules/manifest_stats.nf, pipelines/nextflow/modules/process_gff3.nf, pipelines/nextflow/workflows/additional_seq_prepare/nextflow.config, scripts/setup/docs/build_sphinx_docs.sh
I have done two different ways to apply the check:
1. Simple header check with all the command inside the CI/CD pipeline ([f0dbd9d](https://github.com/Ensembl/ensembl-genomio/pull/94/commits/f0dbd9d79f462dd286c8102387e5bcec3d23b3da))
2. Move code into bash script so the license header can be readable ([59003fd](https://github.com/Ensembl/ensembl-genomio/pull/94/commits/59003fd1b5181a7e029fc77bd0b4f846f55c1a4f))
Finally, I have fixed all the files raised as missing/incorrect license header by the check.
_Note:_ I do not know what was happening with [pipelines/nextflow/modules/manifest_stats.nf](https://github.com/Ensembl/ensembl-genomio/pull/94/files#diff-c8bb64fd707cbd5c3ed84ac9ab343311b3ec9354d006ba10de956978edcd3a8d), but I have had to discard it and add it again from scratch as …
=> Add license header check

scripts/gff_metaparser/gffstruct/seqfeatcomposer.py
Following bc-bio and biopython update, UnknownSeq has been removed: replace with Seq(None) as per https://github.com/biopython/biopython/blob/master/NEWS.rst
=> Deprecated UnknownSeq

cicd/gitlab/parts/python.gitlab-ci.yml
This job was missing the same `only` requirements as every other python job, making it fail because `python:coverage` may not be found (if no Python part of the codebase is changed). Made `pages` extend `.python` description (changing the `stage`) to make sure `python:coverage` is always present when this job is run.
Added trigger when Python pipeline (YAML) is updated (noticed in this PR that this pipeline was not triggered when it had been updated).
=> Fix CI/CD job trigger issues

pipelines/nextflow/modules/process_gff3.nf, pipelines/nextflow/subworkflows/additional_seq_prepare.nf, pipelines/nextflow/subworkflows/genome_prepare/genome_prepare.nf
The previous version accepted 2 tuples, which led to desynchronisation.
Also using named output channels for readability.
=> Process gff3 input only 1 tuple

src/perl/Bio/EnsEMBL/Pipeline/PipeConfig/BRC4_genome_loader_conf.pm
`Bio::EnsEMBL::Pipeline::PipeConfig::BRC4_genome_loader_conf::default_options->{queue_name}` overrides the env one from ancestor `Bio::EnsEMBL::EGPipeline::PipeConfig::EGGeneric_conf`
and defined at [`Bio::EnsEMBL::EGPipeline::PrivateConfDetails::Impl`](https://github.com/Ensembl/ensembl-production-imported/blob/main/lib/perl/Bio/EnsEMBL/EGPipeline/PrivateConfDetails/Impl.pm.example)
=> BRC4_genome_loader: commenting out default queue name to stop overriding env one

pipelines/nextflow/modules/manifest/manifest_stats.nf, pipelines/nextflow/subworkflows/additional_seq_prepare/main.nf, pipelines/nextflow/subworkflows/genome_prepare/main.nf, pipelines/nextflow/subworkflows/genome_prepare/meta.yml, pipelines/nextflow/tests/test_genome_prepare.yml, pipelines/nextflow/workflows/genome_prepare/main.nf, pipelines/nextflow/workflows/genome_prepare/nextflow.config
Only for assembly check,
so not used by sequence_addition
Set to 0 to skip the check
This is useful for e.g. the full pipeline run check (prevent failure, do not need to get data from NCBI, and ensure the stats file is not going to change).
=> Add ncbi_check option

config/gff_metaparser/metaparser.conf, config/gff_metaparser/metaparser/cds_with_parent_id.patch, config/gff_metaparser/metaparser/flybase.conf
preserving "cds/parent" rule in metaparser.conf to keep CDSs with no IDs
=> preserving "cds/parent" rule in metaparser.conf to keep CDSs with no IDs

config/external_db_map/default.txt
Change following the patch we had to do to _D. melanogaster_ core db in e110 ([staging-patches:PR#599](https://github.com/Ensembl/staging-patches/pull/599)).
=> Reduce flybase_annotation_id keys length

cicd/gitlab/dot.gitlab-ci.yml, cicd/gitlab/parts/flatfile.gitlab-ci.yml, cicd/scripts/check_flatfile.py, pipelines/nextflow/subworkflows/patch_build_post_process/meta.yml
For now I have only included JSON and YAML, but I have tried to design the script to be expanded to other formats as we see fit.
_Note:_ I have expanded the accepted YAML format to ensure it does not complain to the current GitLab tags we are using in our CI/CD pipelines. More might need to be added in the future.
=> Added CI/CD flat file tests

cicd/gitlab/dot.gitlab-ci.yml, cicd/gitlab/parts/perl.gitlab-ci.yml, scripts/load_fann.pl, src/perl/Bio/EnsEMBL/Pipeline/Runnable/BRC4/DumpSeqRegionJson.pm, src/perl/Bio/EnsEMBL/Pipeline/Runnable/EG/LoadGFF3/AnalysisSetup.pm, src/perl/Bio/EnsEMBL/Pipeline/Runnable/EG/LoadGFF3/Base.pm
Although temporary, I believe it is still important to have `perlcritic` running as part of our CI/CD for the time being, since there is still debugging/small dev happening.
After running `perlcritic` I have tried to address all the issues raised. I believe none should produce a different outcome with the exception of the `eval` line change in `src/perl/Bio/EnsEMBL/Pipeline/Runnable/EG/LoadGFF3/AddSynonyms.pm`, since I'm not sure where the `{}` should be introduced (). Exact message error:
```
[BuiltinFunctions::ProhibitStringyEval] Expression form of "eval" at line 182, column 29.  (Severity: 5)
```
And its extended version:
```
The string form of `eval' is recompiled every time it is executed,
whereas the block form is only compiled once. Also, the string form
doesn't give compile-time …
```
=> Add Perl to our CI/CD

pipelines/nextflow/subworkflows/patch_build_post_process/main.nf
Include a useful intermediate file, containing the IDs of the new transcripts for genes where the stable ID is conserved.
=> Include transcript ids to allocate

src/python/ensembl/io/genomio/utils/archive_utils.py, src/python/ensembl/io/genomio/utils/json_utils.py
- ".gz" can also be found in ".tar.gz" for instance, so the latter needs to be checked always first
- `Path.suffix` would only grab the last ".*", ignoring cases such as ".tar.gz"
- `shutil.unpack_archive()` creates the destination if it does not exist, so this behaviour has been replicated in the other cases for consistency
=> Bugfixes and code updated on GenomIO utils

.github/workflows/sphinx_doc_generation.yaml, scripts/setup/docs/Makefile_ghpages, scripts/setup/docs/build_docs_gh-pages.sh
Contents of PR:
- single YAML file to set up config of workflow. This workflow is restricted to trigger only when a PR is made to main. PR includes main as accepted branch, and excludes any branch linked to current Ensmetazoa team members. 
- Slight modification to sphinx build script (addition of new script called in context of workflow.)
- Workflow includes params set to reuse python installation deps with -cache to speed up re workflow after initial run.
=> Addition of workflow config for sphinx doc generation

.github/workflows/sphinx_doc_generation.yaml
Single small change on workflow config to change:
Workflow Trigger event from pull_request to push. 
This was done as it wasn't clear wether simply opening a PR to main would trigger the workflow. Given a push is performed upon merging said PR, perhaps this is the activity we actually need.
=> Change on event to push not PR

.github/workflows/sphinx_doc_generation.yaml, docs/source/modules.rst
I've noticed that for some reason, Im not sure why but sphinx build was not able to locate the modules.rst file upon building. Meaning a broken 404 link. I've manually added this file to docs/source to see if this fixes this issue. 
Also updated the docs yaml to update the job name banner.
=> Fix to Sphinx build - Failing to find modules.rst 

README.md, cicd/gitlab/parts/python.gitlab-ci.yml, pyproject.toml
This is the best course of action if we want to ensure only the bare minimum tools used in CI/CD are included (but no other libraries that may ease development work). If we want to support a `dev` tag as well that holds `cicd` and `doc` together without explicitly duplicating everything, the best option at the moment is to have a script that can automatically create a `requirements-dev.txt` file every time `pyproject.toml` is updated (so it can be installed with `pip install -r requirements-dev.txt`).
_Note 1:_ not sure if needed, not sure if useful, but worth flagging this up.
_Note 2:_ I have left `ensembl-py` where it is since this is being addressed in another PR.
=> Make a explicit CI/CD tag

pipelines/nextflow/modules/files/publish_output.nf, pipelines/nextflow/modules/genbank/extract_from_gb.nf, pipelines/nextflow/modules/gff3/gff3_validation.nf, pipelines/nextflow/subworkflows/additional_seq_prepare/main.nf, pipelines/nextflow/workflows/additional_seq_prepare/main.nf, src/perl/Bio/EnsEMBL/Pipeline/PipeConfig/BRC4_genome_loader_conf.pm, src/python/ensembl/io/genomio/genbank/extract_from_genbank.py
The main change is to avoid generating an empty GFF3 file early in the pipeline if there are no records to avoid `gt` to fail later on (cannot handle empty GFF3 files). I have opted for this approach because it makes more sense to not flow anything when there is nothing to process (saving compute) than handling empty files, i.e. it requires more manual intervention to asses if the GFF3 was supposed to be empty at that point.
=> Additional B67 updates

pipelines/nextflow/modules/manifest/check_integrity_db.nf, src/python/ensembl/io/genomio/manifest/check_integrity.py
- Implemented ensembl-py logging for manifest module
- Included logging changes to manifest.check_integrity submodule only.
- Updated NXF module to call integrity check with verbose logging as default
=> Merging into parent branch: ens-py logging manifest integrity 

pipelines/nextflow/modules/database/dump_db.nf, pipelines/nextflow/modules/events/dump_events.nf, pipelines/nextflow/modules/fasta/dump_fasta_dna.nf, pipelines/nextflow/modules/fasta/dump_fasta_peptides.nf, pipelines/nextflow/modules/genome_metadata/dump_genome_meta.nf, pipelines/nextflow/modules/genome_metadata/dump_ncbi_stats.nf, pipelines/nextflow/modules/genome_stats/dump_genome_stats.nf, pipelines/nextflow/modules/seq_region/dump_seq_regions.nf, pipelines/nextflow/subworkflows/dump_files/main.nf, pipelines/nextflow/workflows/dumper_pipeline/main.nf
- Use if in the workflows instead of when in the processes
- Pass the selection of files to dump directly instead of as part of the db metadata
=> replace when by if, clearer structure

pipelines/nextflow/workflows/dumper_pipeline/main.nf
One last change to make things clearer I hope:
- Separate choices for SQL and other files: --dump_sql --dump_all_files or --dump_selection
- List of files and their numbers is in one simple map
=> Rewrite dumper parameters

src/python/ensembl/brc4/runnable/load_sequence_data.py
Ignoring "artificial" (like "chunk" or "ensembl_internal") coord systems
and keeping synonyms for the original sequences presented in the initial fasta file
("initial" sequence data, not the chuncked one).
Tested on `ensembl-production-metazoa/meta/109_for_110/rs8t_same` load.
=> fixing issue with RefSeq seq_region synonyms for chuncked assemblies

src/perl/Bio/EnsEMBL/Pipeline/PipeConfig/BRC4_genome_dumper_conf.pm
Just replace the `json_validator` with the new version (simpler) in the ehive version for backward compatibility
=> Use new json validator in ehive dumper

cicd/scripts/check_license.py
Test files should be minimal and normally these do not require the license header to be attached to them, so we can relax this requirement for such files.
=> Add exclusion directory list to license header checks

src/python/ensembl/io/genomio/data/gff3/biotypes.json, src/python/ensembl/io/genomio/gff3/simplifier.py
The GFF3 part of the hackthon branch introduce some changes that break how features are handled (because of a change in the order of operations). This is some code in the simplifier module which doesn't have tests yet.
Details:
In the current (faulty) order of operation, the features that have a biotype mRNA, transcripts, etc. or CDS without a gene parent are deemed unsupported and the GFF3 parsing fails. We do have two operations `transcript_gene()` and `CDS_gene()` that move the mRNA, CDS etc. under a gene parent, but right now they are done after checking for the biotype.
In this patch I reorder the operations with clearer labels, and put back the two operations that add a gene parent before the check for unsupported gene features.
NB: I recommend looking at the full …
=> Fix GFF3 parsing for naked transcripts and CDSs

cicd/gitlab/dot.gitlab-ci.yml, cicd/gitlab/parts/python.gitlab-ci.yml
Instead of setting only the version as the environment variable content I have opted for the whole image information in case we want to use a different source in the future.
=> Make the Python image a CI/CD variable

cicd/gitlab/dot.gitlab-ci.yml, cicd/gitlab/parts/python.gitlab-ci.yml, src/python/ensembl/io/genomio/manifest/check_integrity.py
A quick PR to both apply black and show how to use the __doc__ for the parser description to avoid redundancy.
=> Use module doc for parser description

scripts/brc4/patch_build/osid_add_organisms.py
This script can now be used to update the pattern of stable_ids stored in OSID: it can do so as long as we do not also include start for gene and transcript (because in this case it will not work, otherwise it would change what has already been allocated).
With some clean up.
=> Update stable id pattern in OSID

cicd/gitlab/parts/python.gitlab-ci.yml
With the current approach is quite difficult to see the files that would be changed (if any). Removing this argument should resolve this issue. E.g. https://gitlab.ebi.ac.uk/vectorbase/ensembl-genomio/-/jobs/1555497
=> Remove --verbose option for black

src/python/ensembl/io/genomio/manifest/check_integrity.py, src/python/ensembl/io/genomio/manifest/compute_stats.py
Instead of dying when stats do not match, simply create a stats error file that we can easily see after the script (and the prepare genome pipeline) is over.
=> Don't fail but write a stats error file

mkdocs.yml
Followed the suggestion found in https://stackoverflow.com/questions/67983304/how-to-use-build-date-utc-for-copyright-year-in-mkdocs-yml
=> Add javascript to always have the Copyright up to date in the documentation

src/python/ensembl/io/genomio/genome_stats/dump.py, src/python/tests/genome_stats/test_dump.py, src/python/tests/genome_stats/test_dump/genome_stats.json
This unit tests is designed to avoid needed a database connection and, therefore, a core database. However, to be able to test the code correctly the queries have been hardcoded in the test file. I will produce an alternative without the mocking and an actual test core db in a separate PR.
I have also taken the opportunity to refactor the source module in some points to make the code more readable.
_Coverage:_ 100% of the module tested.
=> Add unit test for ensembl.io.genomio.genome_stats.dump module

src/python/tests/conftest.py, src/python/tests/gff3/test_gene_merger.py
Compare two files and show a unified diff if they do differ. Pytest output looks like this if the assertion fails:
```
AssertionError: Test-made and expected files differ
--- Test-made file
+++ Expected file
@@ -1,3 +1,3 @@
A
-B1
+B2
C  
assert False
```
[...]
```
FAILED test_xxx.py::test_xxx[name] - AssertionError: Test-made and expected files differ
```
=> Create assert_files fixture

pipelines/nextflow/workflows/additional_seq_prepare/main.nf
The `publish_dir` was changed to use an explicit value in the prepare_genome pipeline in a previous PR, but the addition_prepare pipeline that used the same module did not have that changed
(NB: this broke the Nextflow test `test_addition_prepare.yml`, now fixed)
=> Set publish dir for addition pipeline too

pipelines/nextflow/modules/database/db_factory.nf
Bugfix: the join part fails if no db_list is provided
(part of the dumper pipeline; to reproduce the bug, run the pipeline with no `--db_list` parameter)
=> Fix db_list when not defined

pyproject.toml, src/python/ensembl/io/genomio/annotation/load.py
This script is to be used to compare the descriptions between a core database and a functional_annotation.json file generated by the prepare genome pipeline.
If there are differences, they are reported, and the script can do 2 things:
* Write out the differences (basically the stable_id and the different descriptions)
* Update the core database to replace the descriptions
The current implementation can replace descriptions for genes and transcripts.
This can be thought as a basis for a full fledge functional annotation loader (the things missing are basically the xrefs, the translations and the mobile elements).
=> Annotation script to update descriptions

src/python/ensembl/io/genomio/genome_metadata/prepare.py
Add a quick check for the response (to die if something went wrong), and fix the url used for the ENA API: double `//` do not work.
=> Fix ENA API

pipelines/nextflow/modules/genome_metadata/prepare_genome_metadata.nf, pipelines/nextflow/modules/seq_region/process_seq_region.nf, pipelines/nextflow/tests/workflows/test_genome_prepare_brc_mode_off.yml, pipelines/nextflow/tests/workflows/test_genome_prepare_brc_mode_on.yml, src/python/ensembl/io/genomio/genome_metadata/prepare.py, src/python/ensembl/io/genomio/seq_region/prepare.py
When some external services are done, some parts of the pipeline may fail (`genome_metadata` and `seq_region` prepare in particular). We'd also prefer not to query those services when we run a mock pipeline.
This PR adds a `--mock_run` option to 2 prepare scripts that query ENA, and use it in `stub` commands for the corresponding nextflow modules. Because the output differs in the end, I've also updated the final md5sum for the seq region file.
=> Add mocks for pipeline tests

src/python/ensembl/io/genomio/data/schemas/genome.json, src/python/ensembl/io/genomio/genome_metadata/dump.py, src/python/tests/genome_metadata/test_dump.py
Updated all methods (review docstrings, improve readability and reduce code complexity) and added unit tests for all of them.
In the case of `get_genome_metadata()` the rework whilst may not be as efficient as the previous code, I believe it is more readable and allows for further meta table checks in case the data found there does not match the expected format, e.g. is `species` meta key always has a subkey but there is an entry without, a `ValueError` is raised.
Added to `__all__` one of the functions that was missing.
=> Add unit test for ensembl.io.genomio.genome_metadata.dump module

pyproject.toml
`pytest` 8.1+ has introduced a change that makes it incompatible with the latest `pytest-workflow`. This deprecation was not announced by `pytest` so the other library (active) could not update in time (update in progress now).
=> Temporal pytest version restriction

src/python/ensembl/io/genomio/seq_region/prepare.py
The URL for the ENA API has changed. I also changed the checks to better explain what is wrong.
=> ENA request: fix new URL + better check

src/python/ensembl/io/genomio/genome_metadata/dump.py
Temporary way to dump GCF accession to genome metadata until we actually change the accession itself
=> Dump GCF accession if provider is RefSeq

src/python/ensembl/io/genomio/gff3/process.py
The default of GFFSimplifier is to make IDs if the ones it finds are invalid/missing. The gff3_process script however defaults to the opposite, so this PR reverses the default for the gff3_process script with `--fail_missing_stable_ids`.
=> Reverse default in CLI for ID generation

src/python/ensembl/io/genomio/data/gff3/biotypes.json, src/python/ensembl/io/genomio/gff3/id_allocator.py, src/python/ensembl/io/genomio/gff3/simplifier.py
Move the miRNA from under the primary_transcript, to its own gene, so that it can be imported in Ensembl core database.
Also change the default to fail if an unsupported type is found.
=> Support for miRNA genes

pipelines/nextflow/modules/genome_metadata/accession_metadata.nf, pipelines/nextflow/modules/genome_metadata/datasets_metadata.nf, pipelines/nextflow/modules/genome_metadata/prepare_genome_metadata.nf, pipelines/nextflow/subworkflows/genome_prepare/main.nf, pipelines/nextflow/workflows/genome_prepare/main.nf, src/python/ensembl/io/genomio/genome_metadata/prepare.py, src/python/tests/genome_metadata/test_prepare.py, src/python/tests/genome_metadata/test_prepare/default_taxonomy.xml, src/python/tests/genome_metadata/test_prepare/genome_accession.json, src/python/tests/genome_metadata/test_prepare/genome_accession_ncbi.json, src/python/tests/genome_metadata/test_prepare/genome_accession_updated.json, src/python/tests/genome_metadata/test_prepare/ncbi_meta.json, src/python/tests/genome_metadata/test_prepare/no_taxonomy.xml, src/python/tests/genome_metadata/test_prepare/strain_taxonomy.xml, src/python/tests/genome_metadata/test_prepare/updated_genome_ncbi.json
Instead of using a request to the ENA API, get the metadata from the JSON report from NCBI's datasets.
This simplifies the code (and the tests) since we don't need to check/mock that part.
Now we need to download the dataset file before running the script, so I've updated the Nextflow module to do so.
I've also modified the prepare part in to incorporate the "annotation" part of the genome json if there are annotations, and we can use this information to determine how many files we expect at the end of the Nextflow pipeline (3 or 6).
Also note that I've replaced `concat` by `mix`, since `concat` actually waits for the whole list of each channel before passing the next one, and mix push they as they arrive.
This change makes the `groupTuple()` work correctly: now instead of waiting for all …
=> Prepare genome metadata with datasets

cicd/gitlab/parts/python.gitlab-ci.yml
Black is run on all folders, but CICD is not run when scripts/ Python scripts are modified. This lead to issues later on.
=> CICD when scripts are modified

src/python/ensembl/io/genomio/manifest/check_integrity.py
The current integrity has a major bug where the integrity errors found are not reported (only the files parsing errors are).
Explanation: there are 2 lists of errors: manifest.errors (from parsing the files) and integrity.errors (from comparing the data). Only the first one raised an exception, the second one was not raised or shown in the logs.
This PR ensure both are raised (and the manifest issues are raised first).
Also fix the way errors are stored in integrity.errors.
=> Fix integrity error report

src/python/ensembl/io/genomio/manifest/check_integrity.py
2 fixes:
- Use the synonyms from the seq_region json in case the GFF uses synonyms
- The number of only_feat seq regions was incorrect
=> Fix seq compare in integrity

containers/ncbi_datasets_v16.10.0.def, pyproject.toml, src/python/ensembl/io/genomio/assembly/__init__.py, src/python/ensembl/io/genomio/assembly/status.py
This submodule allows for users to:
- track the assembly 'status' of INSDC accessions. 
- Status results obtained from assembly summary reports (JSON)
- Users can request status checks by providing either A) list of core(s) dbs; or B) list of GCA/GCF accessions
- Status tracking is achieved via use of containerised ncbi 'datasets' and integration of singularity to python (via [spthon](https://github.com/singularityhub/singularity-cli))
- ncbi datasets is set up to perform batched searches, can be customised. Currently set to batches of n=100. 
- The results of said status check is stored for user inspection as TSV file. 
- Status of given INSDC accessions also retrieves (where it exists) the associated 'paired' assembly
This PR comprises the first iteration of assembly status tracking …
=> Addition of a new sub-module 'status' to assembly module. 

src/perl/Bio/EnsEMBL/Pipeline/Runnable/EG/LoadGFF3/ApplySeqEdits.pm
Credited to its creator, as it should be :smile_cat:
=> Allow both translation and transcript ID in cap_protein.fasta

src/python/ensembl/io/genomio/gff3/extract_annotation.py, src/python/ensembl/io/genomio/gff3/simplifier.py, src/python/tests/gff3/test_extract_annotation.py, src/python/tests/gff3/test_simplifier.py
Fix a bug where the `provider_name` was not properly given to the `FunctionalAnnotations` object. Replace the `genome` attrib with a simpler `provider_name` string.
Also add a part to infer the `provider_name` from the `assembly.accession`, which is mandatory from the metadata, in case the `assembly.provider_name`, which is optional, is not provided.
Update and expand the tests
=> Fix assembly provider for annotation

src/python/ensembl/io/genomio/gff3/id_allocator.py, src/python/ensembl/io/genomio/gff3/simplifier.py
Change how we handle RefSeq gene IDs:
* The ID is valid if it starts with LOC*
* Otherwise we fallback to GeneID_*
* If there is no Dbxref GeneID, we generate a new ID
Rational: the current ID validity check is too broad for RefSeq so we sometimes we end up with some gene names as IDs. Restricting to LOC* and falling back directly to GeneIDs will avoid any such gene names to be used a IDs.
=> RefSeq gene IDs update

src/python/ensembl/io/genomio/manifest/check_integrity.py
* ~~Separate `add_error` and `add_errors` to avoid confusion (and better type hint)~~ Unified `add_errors()`
* Return list of errors instead of numbers (homogeneity)
* Better reports errors when 2 checks are done (e.g. Translation Fasta vs GFF with or without pseudogenes/IG genes)
* Support for IG genes that have a CDS but have no sequence in the peptide FASTA file
=> Better integrity check

src/python/ensembl/io/genomio/assembly/status.py
Due to ncbi updating their version of datasets tool since assembly tracker was first introduced, meant when running assembly tracker caused it to crash out as a result of the returned query type test failing (expected _string_) but got a _list_. 
The result contained the JSONl assembly query in addition to:
Announcement message reporting a newer version of datasets was available. 
Fix checks result type returned and removes user announcement messages when using non-latest versions of datasets.
=> Bug fix for assembly tracker

cicd/gitlab/dot.gitlab-ci.yml
It seems some available shared runners do now have Docker, which was causing failure of some of our jobs. Setting a default job tack to request all of them to have docker should address this problem.
=> Set GitLab CI/CD runner tag to ensure the correct job environment

src/python/tests/genbank/test_download.py, src/python/tests/gff3/test_id_allocator.py
`tmp_dir` was created long time ago when `tmp_path` was not there with its current functionality. This is to align with the drop of such fixture in ensembl-py (https://github.com/Ensembl/ensembl-py/pull/47).
=> Replace ensembl-py tmp_dir fixture by pytest tmp_path

src/perl/Bio/EnsEMBL/Pipeline/Runnable/EG/LoadGFF3/ReportSeqEdits.pm
The FASTA file that we get for the patch build from Apollo usually uses the mRNA IDs for the protein sequences. Instead of asking everytime to chagne the FASTA file to use the protein IDs instead, I've modified our loader to allow matching protein IDs (already loaded in the core database) using the mRNA/transcript IDs from the Apollo FASTA file.
Additionally, I've removed the log "Not in file" which can contain a lot of sequences (since the patch build FASTA file only contains the genes that have changed). This prevents that whole list of sequences to fill the email at the end of the loading.
=> Allow mapping mRNA IDs from the Apollo FASTA file to protein IDs

src/python/ensembl/io/genomio/gff3/exceptions.py, src/python/ensembl/io/genomio/gff3/simplifier.py, src/python/tests/gff3/test_simplifier.py
We get the gene segment information from the transcript itself, but in some cases the information is in their CDS, this PR adds this extra check.
Rewrite the code with a new exception `GeneSegmentError` when we can't get the information to make the proper biotype.
=> Gene segment info from the CDS

pipelines/nextflow/modules/manifest/integrity.nf, src/python/ensembl/io/genomio/manifest/check_integrity.py
Add a `--no_fail` argument to the `check_integrity.py` script. The default behaviour is still to fail when an integrity fails (most notably for the genome loader).
This PR changes the default manifest integrity Nextflow module to use that `--no_fail` option so as to not kill the whole pipeline when an integrity check fails. Instead, `integrity.out` files are created in each folder and only kept if there have been errors. .
Impacted pipelines: prepare_genome, additional_seq_prepare, dump_files
PS: We should think about writing a final report (sent by email or printed to screen/file) to show what went wrong at the end of a pipeline.
=> Add no_fail option to integrity for nextflow to not die

src/python/ensembl/io/genomio/gff3/extract_annotation.py, src/python/tests/gff3/test_extract_annotation.py
RefSeq specific: transcript descriptions usually have a "transcript variant X1" at their end. When we transfer this description up to the genes, this PR removes it to have a cleaner gene description.
Add this bit to the test.
=> Remove transcript "variant X" when transferring to genes

conftest.py, pyproject.toml, src/python/ensembl/io/genomio/annotation/load.py, src/python/ensembl/io/genomio/database/dbconnection_lite.py, src/python/ensembl/io/genomio/genome_stats/dump.py, src/python/ensembl/io/genomio/seq_region/rename.py
`ensembl-utils` will host the `database` and `plugin` modules previously hosted in `ensembl-py` as of v0.3.0. This PR covers the changes required in our codebase to migrate to this change.
_Note:_ CI/CD checks will not pass until `ensembl-utils` v0.3.0 is out [[link](https://github.com/Ensembl/ensembl-utils/pull/8)].
=> Update GenomIO to use ensembl-utils v0.3.0

pyproject.toml, src/python/ensembl/io/genomio/genbank/extract_data.py, src/python/ensembl/io/genomio/gff3/extract_annotation.py, src/python/ensembl/io/genomio/gff3/features.py, src/python/ensembl/io/genomio/gff3/id_allocator.py, src/python/ensembl/io/genomio/gff3/restructure.py, src/python/ensembl/io/genomio/gff3/simplifier.py, src/python/ensembl/io/genomio/manifest/check_integrity.py, src/python/ensembl/io/genomio/seq_region/prepare.py, src/python/tests/genbank/test_extract_data.py, src/python/tests/genbank/test_extract_data_seq.py, src/python/tests/gff3/test_extract_annotation.py, src/python/tests/gff3/test_id_allocator.py, src/python/tests/gff3/test_restructure.py, src/python/tests/gff3/test_simplifier.py
Remade https://github.com/Ensembl/ensembl-genomio/pull/297 from the latest main.
Various type hints fixes along the way.
One big change: I've added a new `GFFSeqFeature` object, subclass of `Bio.SeqFeature`. The only difference is that this one has an additional attribute "sub_features" that the GFF parser adds.
By replacing every occurrence, we can make sure that we use the correct typing without ignoring the warnings. Bonus benefit: we no longer need to add `sub_features = []` every time we create a `SeqFeature` object.
Other change, similar problem: we used to add an attribute `organelle` to the `SeqRecord`. I've changed it to store this information in the existing `annotations` instead.
I have set the biopython version to 1.3 for now
=> Update code for Biopython 1.84 compatibility

src/python/ensembl/io/genomio/assembly/status.py
Just an update to point to ensemblorg dockerhub instead of sylabs.
=> Update assembly tracker datasets docker URI to ensemblorg

pyproject.toml, src/python/ensembl/brc4/runnable/seqregion_parser.py, src/python/ensembl/io/genomio/assembly/download.py, src/python/ensembl/io/genomio/genome_metadata/prepare.py, src/python/ensembl/io/genomio/genome_stats/dump.py
Add rules for ruff (linter) and fix a few obvious things
=> Add ruff checks

pipelines/nextflow/modules/gff3/gff3_validation.nf, pipelines/nextflow/workflows/nextflow.config
Centralize the containers url in the nextflow.config file. This makes it easier to reuse the containers in various processes using labels if needed, and it's easier to maintain in the long run.
=> Move gt container in main config

pipelines/nextflow/workflows/additional_seq_prepare/nextflow.config, pipelines/nextflow/workflows/genome_prepare/nextflow.config, pipelines/nextflow/workflows/nextflow.config
Only enable singularity on our cluster, i.e. when we use the profiles `slurm` or `lsf`, instead of systematically. This means that singularity is no longer enabled by default when run locally (by default without a `--profile`), in particular where it is not available (e.g. on a Mac).
NB: on Mac you can use Docker for processes that have a container, so you should add this to your `~/.nextflow/config`:
```
docker.enabled = true
```
(Unless you want to use you current environment)
This should make all our pipelines (and their tests) run on both clusters and laptops without changing the default configs
=> Move singularity enabled in slurm/lsf profiles

pipelines/nextflow/workflows/nextflow.config
Use fixed version to prevent plugin check every time we run the pipeline (in particular when running tests)
=> Update nf-validation to nf-schema

pipelines/nextflow/workflows/nextflow.config
I'm also considering dropping support for LSF since we should be using only SLURM now, but will leave that decision to the reviewer.
=> Set same behaviour as later Nextflow versions (23.05+)

README.md
GitLab clone where the CI pipeline is run is only available internally.
=> Use shields badge for branch checks

src/python/tests/assembly/test_download.py
After having rebuild my venv, I encountered an issue with these `assert_call` calls. I've made a quick fix but we should look at this test more closely to make sure it's correctly testing with these changes.
=> Fix assert_called

pyproject.toml, src/python/ensembl/io/genomio/database/core_server.py, src/python/ensembl/io/genomio/genome_stats/dump.py, src/python/tests/database/test_core_server.py, src/python/tests/genome_stats/test_dump.py
Make various fixes to ensure we can upgrade to ensembl-py 2.1, which allows using SQLalchemy 2.0 and not just 1.4
Main changes are to the tests for genome_stats/dump and core_server:
- `func.count` is flagged erronously by pylint as `not-callable` (cf https://github.com/sqlalchemy/sqlalchemy/issues/9189), so added an ignore comment
- Use `func.count()` with argument (not needed)
- Replace session->execute() with session->connection->execute() (with an additional MockConnection)
- Mypy does not like how we overload `MockSession` with a different `execute()`, so added mypy ignore override
PS: We should plan to rewrite the genome_stats/dump with UniTestDB instead to avoid those mypy/pylint flags
=> Upgrade to ensembl-py 2.1

config/gff_metaparser/valid_structures.conf, src/python/ensembl/brc4/runnable/load_sequence_data.py, src/python/ensembl/io/genomio/fasta/chunk.py, src/python/tests/fasta/test_chunk.py
The chunking code was broken, though that didn't affect writing to individual chunk files.
But when writing to the joined output file it was reopened for writing for each chunk, possibly losing previous chunks data.
=> genomio.fasta.chunk fixed, refactored, tests added

pyproject.toml, src/python/ensembl/io/genomio/assembly/status.py, src/python/ensembl/io/genomio/database/dbconnection_lite.py, src/python/ensembl/io/genomio/events/load.py, src/python/ensembl/io/genomio/fasta/chunk.py, src/python/ensembl/io/genomio/genbank/download.py, src/python/ensembl/io/genomio/genbank/extract_data.py, src/python/ensembl/io/genomio/gff3/exceptions.py, src/python/ensembl/io/genomio/gff3/extract_annotation.py, src/python/ensembl/io/genomio/gff3/restructure.py, src/python/ensembl/io/genomio/manifest/check_integrity.py, src/python/ensembl/io/genomio/manifest/compute_stats.py, src/python/ensembl/io/genomio/manifest/generate.py, src/python/ensembl/io/genomio/utils/json_utils.py, src/python/tests/annotation/test_update_description.py, src/python/tests/assembly/test_download.py, src/python/tests/database/test_core_server.py, src/python/tests/database/test_dbconnection_lite.py, src/python/tests/fasta/test_chunk.py, src/python/tests/genbank/test_extract_data_seq.py, src/python/tests/genome_metadata/test_prepare.py, src/python/tests/genome_stats/test_dump.py
On top of the added configuration of `mypy`:
- Updated codebase accordingly
- Fixed some typos
- Updated some docstrings
It is interesting how forcing this has not only flagged a few things we missed during code review, but also a few minor issues we had in the code (and most likely a couple of bugs).
=> Require type hints in every method and function

pyproject.toml
Fix ensembl-py ORM to allow dumps from MySQL core dbs.
Also upgrade ensembl-utils to its latest version.
=> Upgrade ensembl-py to 2.1.2 to fix seq_region dump bug

README.md
It seems there is no alternative solution to this problem, and it is better to have working links in `pypi` than links working for every branch in the repository.
=> Revert relative paths to absolute paths so they work properly in pypi

src/python/ensembl/io/genomio/__init__.py
Genomio library release version requires changes to __init__.py. 
- Change from release version 1.2.0 (published  July 2024) to release v.1.3.0
=> Increase genomio version to 1.3.0

docs/index.md, src/python/ensembl/io/genomio/assembly/download.py, src/python/ensembl/io/genomio/database/factory.py, src/python/ensembl/io/genomio/external_db/__init__.py
There were some out of sync function signatures remaining in two modules which caused mkdocs to complain and ultimately fail to deply to gh-pages.
Modules affected:
- assembly/download 
- database/factory
Additionally, added missing __init__.py for external_db (key reason for killed mkdocs deployment)
=> Fix for mkdocs deployment

src/python/ensembl/io/genomio/__init__.py
Mkdocs failed to deploy following genomio release v1.3.0, linked to issues tackled in [PR440](https://github.com/Ensembl/ensembl-genomio/pull/440). However Github actions jobs can't be just rerun following PR merge post repo release, being linked directly to initial commits prior to new initial release publishing. 
Resolution - Trigger new release, based on minor version 1.3.0 -> 1.3.1 bug fix
=> Bugfix mkdocs, minor version change (v1.3.1)

pyproject.toml, src/python/ensembl/io/genomio/assembly/status.py, src/python/ensembl/io/genomio/gff3/overlaps.py
I was the one proposing the addition of common arguments via loop for each subparser, but reviewing the documentation I have found the "correct" way to implement it, so I have fixed it in the two places where we had it.
=> Use parents feature instead of loop for subparsers

src/python/ensembl/io/genomio/assembly/status.py
There was a bug with the use of the download dir path for datasets cli. 
- In place was param output_file, but it was not update in two function calls. 
- I've change the name of this param to better represent the actual function, its not a file naming param after all. Designating this param as 'datasets_dir' makes more sense to me.
=> Bugfix and output param name change

pyproject.toml, src/python/ensembl/io/genomio/database/factory.py, src/python/tests/database/test_factory.py
This is a showcase of how we could refactor our `main()` methods if we want to follow a path where logic can be left in `main()` but testing everything, argument parsing included (without having to go to the extent of using `subprocess`).
=> Update database.factory.main() function to test all its contents

pyproject.toml, src/python/ensembl/io/genomio/annotation/update_description.py, src/python/ensembl/io/genomio/database/core_server.py, src/python/ensembl/io/genomio/fasta/chunk.py, src/python/ensembl/io/genomio/gff3/features.py, src/python/ensembl/io/genomio/gff3/simplifier.py, src/python/ensembl/io/genomio/manifest/check_integrity.py, src/python/ensembl/io/genomio/seq_region/prepare.py, src/python/tests/annotation/test_update_description.py, src/python/tests/assembly/test_download.py, src/python/tests/assembly/test_status.py, src/python/tests/database/test_core_server.py, src/python/tests/database/test_factory.py, src/python/tests/fasta/test_chunk.py, src/python/tests/fasta/test_process.py, src/python/tests/genbank/test_extract_data.py, src/python/tests/genbank/test_extract_data_seq.py, src/python/tests/genome_metadata/test_extend.py, src/python/tests/genome_metadata/test_prepare.py, src/python/tests/gff3/test_extract_annotation.py, src/python/tests/gff3/test_simplifier.py, src/python/tests/seq_region/test_collection.py, src/python/tests/seq_region/test_dump.py, src/python/tests/seq_region/test_prepare.py
But ignore the issue in unit tests, since it is not relevant in that case.
=> Update GenomIO to avoid too many positional arguments

pyproject.toml, src/python/ensembl/io/genomio/__init__.py, src/python/ensembl/io/genomio/database/__init__.py, src/python/ensembl/io/genomio/database/factory.py, src/python/ensembl/io/genomio/database/meta_getter.py
This is a new module designed to take a defined set of input meta.meta_keys (Input file), and directly query a single core database on those keys. 
- For now, the module requires an input file but in the future it might be good to add the option of passing a list of keys separated by ',' 
- The module dumps the returned keys (1 or more if returned a value from query) in JSON format to stdout. 
- Implemented with a single function called within main().
- Also require the genomio release version to be changed from 1.4.0 to 1.4.1 to allow generation of a container and inclusion of this functionality in BUSCO NXF pipeline.
=> Add new module for DB meta data querying

cicd/gitlab/dot.gitlab-ci.yml
The new format will be, for instance, `v1.5.0_rebuild_a`, which is shorter and starts with the version for better tracking.
=> Update commit tag format when rebuilding docker containers

cicd/gitlab/dot.gitlab-ci.yml
Merge changes in main with Jorges branch to add versioning to ensembl/genomio/io entry points.
- Permits manual triggering for creation of containers via genomio python version CICD variable pattern for container rebuilds.
=> Sync add-version with main (updated CICD container trigger) 

scripts/gff_metaparser/genmetaconf/metaconf.py
use
```
update meta set meta_key = "organism.production_name" where meta_key = "organism.ensembl_name";
```
to fix meta keys for the already loaded cores
=> using proper "organism.production_name" metakey in the config generator
